export const slice6StateMatrix = {
  goals: [
    "no primary",
    "ordinary comparison",
    "positive progress",
    "negative progress",
    "zero change",
    "failed refresh",
    "stale/not-current",
    "protected-floor breach",
    "negative cash flow",
    "expired pace",
    "on pace",
    "completed goal",
  ],
  retirement: [
    "works",
    "essentials only",
    "bridge break",
    "shortfall",
    "operational goals excluded",
    "named immutable goal included",
    "stale profile edit",
    "no snapshots",
    "many snapshots",
  ],
  lab: [
    "seed chooser",
    "blank seed",
    "current-goal seed",
    "retirement-result seed",
    "ordinary experiment",
    "stale promotion",
    "confirmed promotion",
    "legacy combined scenario",
    "many snapshots",
  ],
  moneyUtilities: [
    "empty accounts",
    "populated Overview",
    "unavailable investment performance",
    "available investment performance",
    "Review with issues",
    "Add account with no Plaid connection",
    "failed/partial update status",
  ],
} as const;

export const requiredCriticalEvidence = [
  "failed or partial refresh",
  "stale source state",
  "missing primary goal",
  "protected-floor breach",
  "negative recurring cash flow",
  "expired required pace",
  "completed goal",
  "Retirement bridge break",
  "Retirement shortfall",
  "unavailable investment performance",
  "stale promotion preview",
  "failed promotion confirmation",
  "legacy combined scenario label",
  "missing or unavailable source evidence",
] as const;

export const retiredDuplicateCopy = [
  "goal_mutation=false",
  "retirement_mutation=false",
  "applied=false",
  "See when work can become optional under explicit assumptions.",
] as const;
