export const slice6StateMatrix = {
  navigation: [
    "Cash Flow default and first",
    "Everyday exact order",
    "Details exact order",
    "Planning supporting order",
    "conditional Review count",
    "mobile active reveal and Plaid hash reachability",
  ],
  goals: [
    "no primary",
    "ordinary comparison",
    "positive progress",
    "negative progress",
    "zero change",
    "failed refresh",
    "stale/not-current",
    "protected-floor breach",
    "negative cash flow",
    "expired pace",
    "on pace",
    "completed goal",
  ],
  retirement: [
    "funded through plan",
    "essentials only",
    "pre-retirement accessible cash gap",
    "post-work accessible bridge gap",
    "raw shortfall with retained assets",
    "true terminal exhaustion",
    "missing presentation evidence",
    "saved snapshot presentation",
    "positive $1.17M late-life balance",
  ],
  lab: [
    "seed chooser",
    "blank seed",
    "current-goal seed",
    "retirement-result seed",
    "funded mission before unfinished mission",
    "only completed missions",
    "disabled and invalid missions",
    "experiment and path reset",
    "explicit funded mission without $0 routes",
    "positive mission with four route formulas",
    "whole-month convention with exact dates",
    "51-whole-month comparison",
    "draft isolation and explicit promotion boundary",
  ],
  presentation: [
    "copy budgets",
    "named collapsed disclosures",
    "print expansion and restoration",
    "keyboard focus order and Escape return",
    "reduced motion",
    "reference-size overflow",
    "exact money without clipping",
  ],
  moneyUtilities: [
    "empty accounts",
    "populated Overview",
    "unavailable investment performance",
    "available investment performance",
    "Review with open $2,153.51 SoFi loan difference",
    "Add account with no Plaid connection",
    "failed/partial update status",
  ],
} as const;

export const requiredCriticalEvidence = [
  "failed or partial refresh",
  "stale source state",
  "missing primary goal",
  "protected-floor breach",
  "negative recurring cash flow",
  "expired required pace",
  "completed goal",
  "Retirement bridge break",
  "Retirement shortfall",
  "unavailable investment performance",
  "stale promotion preview",
  "failed promotion confirmation",
  "legacy combined scenario label",
  "missing or unavailable source evidence",
] as const;

export const retiredDuplicateCopy = [
  "goal_mutation=false",
  "retirement_mutation=false",
  "applied=false",
  "See when work can become optional under explicit assumptions.",
] as const;
