import { useEffect, useState } from "react";
import { request } from "../api";
import type { AccountsDashboard } from "../types";
import "./housing.css";

type Amount = string | null;
type Cost = { name: string; amount: Amount; due: string; kind: "expense" | "deposit"; returned: string | null };
type Scenario = { name: string; sale_price: Amount; payoff: Amount; selling_fees: Amount; sale_date: string; funds_date: string; move_date: string; rent: Amount; rental_extras: Amount; costs: Cost[]; costs_complete: boolean; notes: string };
const moneyKeys = ["condo_amount", "cash", "dedicated_cash", "other_net_assets", "income", "nonhousing", "other_savings", "home_value", "mortgage_balance", "mortgage_payment", "principal_interest", "annual_rate", "owner_extras", "reserve", "monthly_set_aside"] as const;
type MoneyKey = typeof moneyKeys[number];
type Plan = Record<MoneyKey, Amount> & { name: string; destination: string; target_date: string; as_of: string; end_date: string; baseline_complete: boolean; baseline_notes: string; condo_amount_meaning: string; housing_costs_complete: boolean; scenarios: Scenario[] };
type Ending = { date: string; stay_cash: string; move_cash: string; stay_net_worth: string; move_net_worth: string; cash_difference: string; net_worth_difference: string; stay_debt: string; refundable_deposits: string };
type Result = { name: string; unknown: string[]; warnings: string[]; proceeds: Amount; monthly: Record<string, string> | null; transition: { required_monthly: string; needed_now: string; reserve: string; timeline: { date: string; cash: string; shortfall: string; items: { name: string; amount: string; kind: string }[] }[] } | null; comparison: { ending: Ending; periods: Ending[]; lowest_move_cash: string; lowest_cash_date: string } | null };
type Evaluation = { scenarios: Result[] };
type Saved = { id: number; revision: number; plan: Plan; result: Evaluation; updated_at: string };
const labels: Record<MoneyKey, string> = { condo_amount: "Condo amount to clarify", cash: "Liquid cash today", dedicated_cash: "Cash assigned to this plan, including its reserve", other_net_assets: "Other assets minus other debts", income: "Monthly take-home available in cash", nonhousing: "Monthly spending excluding all housing", other_savings: "Monthly savings committed elsewhere", home_value: "Estimated condo value today", mortgage_balance: "Mortgage principal at the baseline date", mortgage_payment: "Total monthly mortgage payment", principal_interest: "Principal and interest part of that payment", annual_rate: "Mortgage interest rate (%)", owner_extras: "Monthly ownership costs outside that payment", reserve: "Cash reserve to protect", monthly_set_aside: "Monthly amount you plan to set aside" };
const dollar = (v: Amount | undefined) => v == null ? "Unknown" : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(Number(v));
function blankScenario(today: string): Scenario { return { name: "Main plan", sale_price: null, payoff: null, selling_fees: null, sale_date: today, funds_date: today, move_date: today, rent: null, rental_extras: null, costs: [], costs_complete: false, notes: "" }; }
function emptyPlan(): Plan {
  const today = new Date().toLocaleDateString("en-CA");
  const end = `${Number(today.slice(0, 4)) + 2}${today.slice(4)}`;
  return { ...Object.fromEntries(moneyKeys.map(k => [k, null])) as Record<MoneyKey, Amount>, name: "My housing move", destination: "", target_date: end, as_of: today, end_date: end, baseline_complete: false, baseline_notes: "", condo_amount_meaning: "unknown", housing_costs_complete: false, scenarios: [blankScenario(end)] };
}

export default function HousingView({ accounts, navigate, onDirty }: { onDirty?: (dirty: boolean) => void; accounts: AccountsDashboard; navigate: (view: "accounts" | "income" | "cash-flow" | "connections" | "review") => void }) {
  const [plans, setPlans] = useState<Saved[]>([]);
  const [plan, setPlan] = useState<Plan>(emptyPlan);
  const [identity, setIdentity] = useState<{ id: number; revision: number } | null>(null);
  const [active, setActive] = useState(0);
  const [result, setResult] = useState<Evaluation | null>(null);
  const [status, setStatus] = useState("");
  const [dirty, setDirty] = useState(false);
  const [busy, setBusy] = useState(false);
  const scenario = plan.scenarios[active];
  useEffect(() => { onDirty?.(dirty); }, [dirty, onDirty]);
  useEffect(() => {
    const protect = (event: BeforeUnloadEvent) => { if (dirty) { event.preventDefault(); event.returnValue = ""; } };
    window.addEventListener("beforeunload", protect);
    return () => window.removeEventListener("beforeunload", protect);
  }, [dirty]);
  useEffect(() => { request<Saved[]>("/api/v2/housing").then(setPlans).catch(() => setStatus("Saved plans could not be loaded. Try reopening Housing Move.")); }, []);
  function change(next: Plan) { setPlan(next); setDirty(true); setResult(null); setStatus("Unsaved changes"); }
  function field<K extends keyof Plan>(key: K, value: Plan[K]) { change({ ...plan, [key]: value }); }
  function scenarioField<K extends keyof Scenario>(key: K, value: Scenario[K]) { change({ ...plan, scenarios: plan.scenarios.map((s, i) => i === active ? { ...s, [key]: value } : s) }); }
  function select(saved: Saved) { setIdentity({ id: saved.id, revision: saved.revision }); setPlan(saved.plan); setActive(0); setResult(saved.result); setDirty(false); setStatus(`Opened saved plan, revision ${saved.revision}. Baseline remains dated ${saved.plan.as_of}.`); }
  async function run(save: boolean) {
    setBusy(true); setStatus("");
    try {
      if (save) {
        const saved = await request<Saved>(`/api/v2/housing${identity ? `/${identity.id}` : ""}`, { method: identity ? "PUT" : "POST", body: JSON.stringify({ revision: identity?.revision ?? 0, plan }) });
        setPlans(previous => [...previous.filter(p => p.id !== saved.id), saved]); select(saved); setActive(active); setStatus("Plan and all alternatives saved.");
      } else { setResult(await request<Evaluation>("/api/v2/housing/preview", { method: "POST", body: JSON.stringify(plan) })); setStatus("Preview updated. Save to preserve your changes."); }
    } catch (e) { setStatus(e instanceof Error ? e.message : "The plan could not be updated."); }
    finally { setBusy(false); }
  }
  const numeric = (key: MoneyKey, help?: string) => <label key={key}>{labels[key]}<input type="number" step={key === "annual_rate" ? "0.0001" : "0.01"} min={key === "other_net_assets" ? undefined : 0} value={plan[key] ?? ""} placeholder="Unknown" onChange={e => field(key, e.target.value || null)} />{help && <small>{help}</small>}</label>;
  const scenarioMoney = (key: "sale_price" | "payoff" | "selling_fees" | "rent" | "rental_extras", label: string) => <label>{label}<input type="number" min="0" step="0.01" value={scenario[key] ?? ""} placeholder="Unknown" onChange={e => scenarioField(key, e.target.value || null)} /></label>;
  const current = result?.scenarios[active];
  return <section className="housing-workspace">
    <header><p className="eyebrow">Planning</p><h1>Housing Move</h1><p>Understand today, plan the sale and compare the life you want. Blank amounts stay unknown; enter zero only when you mean none.</p></header>
    <div className="housing-actions"><button disabled={dirty || busy} onClick={() => { setPlan(emptyPlan()); setIdentity(null); setActive(0); setResult(null); setStatus("New housing goal"); }}>New housing goal</button>
      <label>Saved plans<select value={identity?.id ?? ""} disabled={dirty || busy} onChange={e => { const saved = plans.find(p => p.id === Number(e.target.value)); if (saved) select(saved); }}><option value="">Choose a saved plan</option>{plans.map(p => <option value={p.id} key={p.id}>{p.plan.name}</option>)}</select></label>
      {dirty && <button onClick={() => { const saved = plans.find(p => p.id === identity?.id); if (saved) select(saved); else { setPlan(emptyPlan()); setActive(0); setDirty(false); setResult(null); setStatus("Draft discarded"); } }}>Discard unsaved changes</button>}
    </div>
    <details open><summary>1. Your goal</summary><div className="housing-fields">
      <label>Goal name<input value={plan.name} onChange={e => field("name", e.target.value)} /></label><label>Destination<input value={plan.destination} onChange={e => field("destination", e.target.value)} /></label>
      <label>Target move date<input type="date" value={plan.target_date} onChange={e => field("target_date", e.target.value)} /></label>
      <label>Baseline date<input type="date" value={plan.as_of} onChange={e => field("as_of", e.target.value)} /></label><label>Compare through<input type="date" value={plan.end_date} onChange={e => field("end_date", e.target.value)} /></label>
    </div><button disabled={identity !== null} onClick={() => { setActive(0); change({ ...plan, name: "Long Branch move", destination: "Long Branch", target_date: "2027-09-06", end_date: "2028-09-06", condo_amount: "260000", condo_amount_meaning: "unknown", mortgage_payment: "1776", annual_rate: "6.75", scenarios: [{ ...blankScenario("2027-09-06"), rent: "4000", notes: "Starting brief: about four years into a 30-year mortgage. Confirm payment inclusions, rent inclusions, sale timing and the meaning of $260k. Dates are planning assumptions, not booked events." }] }); }}>Use Long Branch starting brief</button></details>
    <details><summary>2. Today's finances and allocation</summary>
      <p>Tracked accounts: {accounts.accounts.length}. Report date: {accounts.as_of ?? "Unknown"}. Tracked cash: {dollar(accounts.totals.cash)}. Tracked net worth: {dollar(accounts.totals.net_worth)}. These totals do not prove complete coverage.</p>
      <div className="housing-actions">{(["accounts", "income", "cash-flow", "connections", "review"] as const).map((v, i) => <button key={v} disabled={dirty} onClick={() => navigate(v)}>{["Review accounts and dates", "Review income allocations", "Review cash flow", "Add accounts", "Review reconciliation"][i]}</button>)}</div>
      {dirty && <p>Save the draft before leaving to review your baseline.</p>}
      <p>Use those existing views to reconcile amounts below. Historical cash flow is not a recurring budget. All entered amounts are explicit planning estimates; saved baselines do not silently follow later imports.</p>
      <div className="housing-fields">{numeric("cash")}{numeric("dedicated_cash", "A subset of liquid cash covering the move and its reserve. Exclude money dedicated to other goals.")}{numeric("other_net_assets", "Exclude the cash above, condo value and its mortgage. Include remaining investments and other debts; negative is allowed.")}{numeric("income", "Cash take-home after payroll deductions; exclude payroll savings already withheld.")}{numeric("nonhousing", "Include all recurring non-housing spending and other debt payments.")}{numeric("other_savings", "Transfers from this take-home to other savings; these reduce available cash but remain assets.")}</div>
      <label>Sources, dates, missing coverage and assumptions<textarea value={plan.baseline_notes} onChange={e => field("baseline_notes", e.target.value)} /></label>
      <label><input type="checkbox" checked={plan.baseline_complete} onChange={e => field("baseline_complete", e.target.checked)} />I have reviewed baseline coverage and recorded missing information or assumptions.</label>
    </details>
    <details><summary>3. Ownership costs</summary><div className="housing-fields">{numeric("condo_amount")}<label>What does that condo amount mean?<select value={plan.condo_amount_meaning} onChange={e => field("condo_amount_meaning", e.target.value)}><option value="unknown">Still unknown</option><option value="purchase_price">Purchase price</option><option value="estimated_value">Estimated value</option><option value="mortgage_balance">Mortgage balance</option></select></label>{numeric("home_value")}{numeric("mortgage_balance")}{numeric("mortgage_payment", "Total payment including any escrow.")}{numeric("principal_interest", "Exclude escrow here. Used only to calculate debt reduction; not added to spending again.")}{numeric("annual_rate")}{numeric("owner_extras", "HOA, maintenance, utilities, tax and insurance only when outside the payment. Do not repeat escrow.")}</div>
      <label><input type="checkbox" checked={plan.housing_costs_complete} onChange={e => field("housing_costs_complete", e.target.checked)} />I have checked ownership and rental costs, including what the payments already cover.</label>
    </details>
    <details open><summary>4. Sale and rental alternatives</summary><div className="housing-actions"><label>Alternative<select value={active} onChange={e => setActive(Number(e.target.value))}>{plan.scenarios.map((s, i) => <option key={i} value={i}>{s.name}</option>)}</select></label><button disabled={plan.scenarios.length >= 8} onClick={() => { change({ ...plan, scenarios: [...plan.scenarios, { ...structuredClone(scenario), name: `Alternative ${plan.scenarios.length + 1}` }] }); setActive(plan.scenarios.length); }}>Copy as alternative</button></div>
      <div className="housing-fields"><label>Alternative name<input value={scenario.name} onChange={e => scenarioField("name", e.target.value)} /></label>{scenarioMoney("sale_price", "Estimated sale price")}{scenarioMoney("payoff", "Mortgage payoff at closing")}{scenarioMoney("selling_fees", "Total selling expenses")}
      {(["sale_date", "funds_date", "move_date"] as const).map((k, i) => <label key={k}>{["Closing date", "Sale cash available date", "Rental start / move date"][i]}<input type="date" value={scenario[k]} onChange={e => scenarioField(k, e.target.value)} /></label>)}
      {scenarioMoney("rent", "Monthly rent target")}{scenarioMoney("rental_extras", "Monthly costs outside rent")}</div>
      <p>Payoff is a dated quote or explicit estimate, including interest and lender fees. Selling expenses include agent fees, closing costs, concessions and any applicable tax estimate. Record repairs below only once. Rental extras include utilities, parking, fees and insurance only when excluded from rent.</p>
      <label>Sale, payoff, rent and timing sources / assumptions<textarea value={scenario.notes} onChange={e => scenarioField("notes", e.target.value)} /></label>
    </details>
    <details><summary>5. Money needed for the transition</summary><div className="housing-fields">{numeric("reserve", "A protected cash floor, not another expense or a second savings target.")}{numeric("monthly_set_aside", "Saved on monthly anniversaries of the baseline date. Part of savings capacity, not extra income.")}</div>
      <p>Add preparation, moving, lease fees and refundable deposits with payment dates. Rent during overlap is calculated automatically; do not add it again. Add temporary accommodation if selling before moving. Prepaid rent must be offset against the rent budget, not added here as another expense.</p>
      {scenario.costs.map((c, i) => <fieldset key={i}><legend>Transition item {i + 1}</legend><div className="housing-fields"><label>Item name<input value={c.name} onChange={e => scenarioField("costs", scenario.costs.map((x, j) => j === i ? { ...x, name: e.target.value } : x))} /></label><label>Amount<input type="number" min="0" step="0.01" placeholder="Unknown" value={c.amount ?? ""} onChange={e => scenarioField("costs", scenario.costs.map((x, j) => j === i ? { ...x, amount: e.target.value || null } : x))} /></label><label>Needed on<input type="date" value={c.due} onChange={e => scenarioField("costs", scenario.costs.map((x, j) => j === i ? { ...x, due: e.target.value } : x))} /></label><label>Type<select value={c.kind} onChange={e => scenarioField("costs", scenario.costs.map((x, j) => j === i ? { ...x, kind: e.target.value as Cost["kind"], returned: null } : x))}><option value="expense">Expense</option><option value="deposit">Refundable deposit</option></select></label>{c.kind === "deposit" && <label>Expected return date (optional)<input type="date" value={c.returned ?? ""} onChange={e => scenarioField("costs", scenario.costs.map((x, j) => j === i ? { ...x, returned: e.target.value || null } : x))} /></label>}</div><button onClick={() => scenarioField("costs", scenario.costs.filter((_, j) => j !== i))}>Remove item {i + 1}</button></fieldset>)}
      <button disabled={scenario.costs.length >= 40} onClick={() => scenarioField("costs", [...scenario.costs, { name: "", amount: null, due: scenario.move_date, kind: "expense", returned: null }])}>Add transition item</button>
      <label><input type="checkbox" checked={scenario.costs_complete} onChange={e => scenarioField("costs_complete", e.target.checked)} />I have reviewed the transition cost list, including any zero costs.</label>
    </details>
    <div className="housing-actions"><button disabled={busy} onClick={() => void run(false)}>Calculate comparison</button><button disabled={busy} onClick={() => void run(true)}>Save housing goal</button></div><p role="status">{status}</p>
    {current && <section aria-label="Housing results"><h2>Your conditional comparison</h2><p>{plan.as_of} through {plan.end_date}. These are estimates based on entered assumptions, not an affordability verdict.</p>
      {current.unknown.length > 0 && <p>Still unknown: {current.unknown.map(k => labels[k as MoneyKey] ?? k.replaceAll("_", " ")).join(", ")}. Complete projections are withheld.</p>}
      <ul>{current.warnings.map(w => <li key={w}>{w}</li>)}</ul><h3>Sale cash: {dollar(current.proceeds)}</h3><p>Sale price − mortgage payoff − selling expenses. This includes returned equity and is not profit. Negative sale cash is needed at closing.</p>
      {current.monthly && <table><caption>Monthly life after the transition</caption><thead><tr><th>Measure</th><th>Stay</th><th>Move</th></tr></thead><tbody>{[["Housing cash payments", "housing"], ["Total spending and payments", "spending"], ["Savings capacity after other commitments", "capacity"]].map(([label, key]) => <tr key={key}><th>{label}</th><td>{dollar(current.monthly![`stay_${key}`])}</td><td>{dollar(current.monthly![`move_${key}`])}</td></tr>)}</tbody></table>}
      {current.transition && <><h3>Transition funding</h3><p>Required monthly set-aside: {dollar(current.transition.required_monthly)}. Additional cash to dedicate before the first saving date: {dollar(current.transition.needed_now)}. Protected reserve: {dollar(current.transition.reserve)}.</p><p>This dedicated-funds plan is separate from total cash below. It includes sale receipts, dated costs and overlap. Ordinary spending must fit the monthly budget.</p><table><caption>When dedicated cash is needed</caption><thead><tr><th>Date / events</th><th>Dedicated cash remaining</th><th>Below reserve</th></tr></thead><tbody>{current.transition.timeline.map(row => <tr key={row.date}><th>{row.date}{row.items.map((item, i) => <small key={i}>{item.name}: {dollar(item.amount)}</small>)}</th><td>{dollar(row.cash)}</td><td>{dollar(row.shortfall)}</td></tr>)}</tbody></table></>}
      {result && <table><caption>Saved or draft alternatives over the same period</caption><thead><tr><th>Alternative</th><th>Sale cash</th><th>Move savings / month</th><th>Ending cash difference</th><th>Ending net-worth difference</th></tr></thead><tbody>{result.scenarios.map(r => <tr key={r.name}><th>{r.name}</th><td>{dollar(r.proceeds)}</td><td>{dollar(r.monthly?.move_capacity)}</td><td>{dollar(r.comparison?.ending.cash_difference)}</td><td>{dollar(r.comparison?.ending.net_worth_difference)}</td></tr>)}</tbody></table>}
      {current.comparison && <><p>Lowest projected moving cash: {dollar(current.comparison.lowest_move_cash)} on {current.comparison.lowest_cash_date}. {Number(current.comparison.lowest_move_cash) < Number(plan.reserve) ? "Cash falls below your reserve." : "Cash stays at or above your chosen reserve under these assumptions."}</p><table><caption>At {plan.end_date}</caption><thead><tr><th>Measure</th><th>Stay</th><th>Move</th></tr></thead><tbody><tr><th>Liquid cash</th><td>{dollar(current.comparison.ending.stay_cash)}</td><td>{dollar(current.comparison.ending.move_cash)}</td></tr><tr><th>Net worth</th><td>{dollar(current.comparison.ending.stay_net_worth)}</td><td>{dollar(current.comparison.ending.move_net_worth)}</td></tr></tbody></table><details><summary>Monthly cash and net-worth path</summary><table><thead><tr><th>Date</th><th>Stay cash</th><th>Move cash</th><th>Stay net worth</th><th>Move net worth</th></tr></thead><tbody>{current.comparison.periods.map(row => <tr key={row.date}><th>{row.date}</th><td>{dollar(row.stay_cash)}</td><td>{dollar(row.move_cash)}</td><td>{dollar(row.stay_net_worth)}</td><td>{dollar(row.move_net_worth)}</td></tr>)}</tbody></table></details><p>Remaining stay mortgage: {dollar(current.comparison.ending.stay_debt)}. Move refundable deposits: {dollar(current.comparison.ending.refundable_deposits)} (assets, not spendable cash).</p></>}
      <details><summary>How this estimate works</summary><p>Monthly income and spending are spread across calendar days. Ownership ends at closing; rental costs start on the rental date, so both apply during overlap. Mortgage debt reduces on monthly anniversaries using principal-and-interest payment less monthly interest. The closing payoff you enter overrides that estimate for the sale. Positive sale funds awaiting disbursement count as a receivable, never available cash.</p><p>Condo value, other asset values, income and costs are held constant. No appreciation, investment return, future tax benefit or debt changes outside this mortgage are assumed. Savings committed elsewhere remain assets. Reserve and dedicated savings are allocations within cash, not expenses. Unreturned deposits retain full value; record only amounts expected to be refundable.</p></details>
    </section>}
  </section>;
}
